name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cypress dependencies
        run: |
          npm install
          npx cypress install

      - name: Ensure Cypress has execution permissions
        run: chmod +x node_modules/.bin/cypress

      - name: Run Cypress tests
        run: npx cypress run

      - name: List JSON reports
        run: ls cypress/relatorio/*.json || echo "No JSON reports found"

      - name: Generate HTML report
        run: npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/relatorio,timestamp=mmddyyyy_HHMMss

      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: cypress/relatorio/index.html
