name: Cypress Tests

on:
  push:
    branches:
      - main  

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          npm run cy:run  # ou o comando específico para executar Cypress

      - name: List JSON reports
        run: ls cypress/relatorio/.jsons/*.json || echo "No JSON reports found"

      - name: Generate HTML report
        run: npm run cy:report  

      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: cypress/relatorio/index.html  
