name: Cypress Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: List project files
        run: ls -R

      - name: Grant Cypress permissions
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run E2E tests
        run: npx cypress run

      - name: List JSON reports
        run: ls cypress/relatorio/.jsons/*.json || echo "No JSON reports found"
