name: Cypress Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Cypress globally
        run: npm install -g cypress

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: cypress run
